
var spineWasm = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  
  return (
function(spineWasm = {})  {

var Module;Module||(Module=typeof spineWasm !== 'undefined' ? spineWasm : {});var aa,ca;Module.ready=new Promise((a,b)=>{aa=a;ca=b});var da=Object.assign({},Module),p="";"undefined"!=typeof document&&document.currentScript&&(p=document.currentScript.src);_scriptDir&&(p=_scriptDir);0!==p.indexOf("blob:")?p=p.substr(0,p.replace(/[?#].*/,"").lastIndexOf("/")+1):p="";var u=Module.printErr||console.error.bind(console);Object.assign(Module,da);da=null;var w;Module.wasmBinary&&(w=Module.wasmBinary);
var noExitRuntime=Module.noExitRuntime||!0;"object"!=typeof WebAssembly&&y("no native wasm support detected");var ea,fa=!1,ha,z,A,ia,B,C,ja,ka;function la(){var a=ea.buffer;Module.HEAP8=ha=new Int8Array(a);Module.HEAP16=A=new Int16Array(a);Module.HEAP32=B=new Int32Array(a);Module.HEAPU8=z=new Uint8Array(a);Module.HEAPU16=ia=new Uint16Array(a);Module.HEAPU32=C=new Uint32Array(a);Module.HEAPF32=ja=new Float32Array(a);Module.HEAPF64=ka=new Float64Array(a)}var ma,na=[],oa=[],pa=[];
function qa(){var a=Module.preRun.shift();na.unshift(a)}var D=0,ra=null,E=null;function y(a){if(Module.onAbort)Module.onAbort(a);a="Aborted("+a+")";u(a);fa=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ca(a);throw a;}function sa(a){return a.startsWith("data:application/octet-stream;base64,")}var F;F="spine.wasm";if(!sa(F)){var ta=F;F=Module.locateFile?Module.locateFile(ta,p):p+ta}
function ua(a){try{if(a==F&&w)return new Uint8Array(w);throw"both async and sync fetching of the wasm failed";}catch(b){y(b)}}function va(a){return w||"function"!=typeof fetch?Promise.resolve().then(()=>ua(a)):fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>ua(a))}
function wa(a,b,c){return va(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{u("failed to asynchronously prepare wasm: "+d);y(d)})}function xa(a,b){var c=F;return w||"function"!=typeof WebAssembly.instantiateStreaming||sa(c)||"function"!=typeof fetch?wa(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){u("wasm streaming compile failed: "+e);u("falling back to ArrayBuffer instantiation");return wa(c,a,b)}))}
var za={22280:a=>{console.warn("[Spine]",a?ya(a):"")}};function Aa(a){for(;0<a.length;)a.shift()(Module)}function Ba(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError(`Unknown type size: ${a}`);}}var Ca=void 0;function H(a){for(var b="";z[a];)b+=Ca[z[a++]];return b}var I={},J={},Da={};function Ea(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a}
function Fa(a,b){a=Ea(a);return{[a]:function(){return b.apply(this,arguments)}}[a]}function Ga(a){var b=Error,c=Fa(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:`${this.name}: ${this.message}`};return c}var K=void 0;function L(a){throw new K(a);}var Ha=void 0;
function Ia(a){throw new Ha(a);}function N(a,b,c){function d(f){f=c(f);f.length!==a.length&&Ia("Mismatched type converter count");for(var k=0;k<a.length;++k)O(a[k],f[k])}a.forEach(function(f){Da[f]=b});var e=Array(b.length),g=[],h=0;b.forEach((f,k)=>{J.hasOwnProperty(f)?e[k]=J[f]:(g.push(f),I.hasOwnProperty(f)||(I[f]=[]),I[f].push(()=>{e[k]=J[f];++h;h===g.length&&d(e)}))});0===g.length&&d(e)}
function O(a,b,c={}){if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||L(`type "${d}" must have a positive integer typeid pointer`);if(J.hasOwnProperty(a)){if(c.na)return;L(`Cannot register type '${d}' twice`)}J[a]=b;delete Da[a];I.hasOwnProperty(a)&&(b=I[a],delete I[a],b.forEach(e=>e()))}function Ja(a){L(a.I.L.J.name+" instance already deleted")}var Ka=!1;function La(){}
function Ma(a){--a.count.value;0===a.count.value&&(a.O?a.P.V(a.O):a.L.J.V(a.K))}function Na(a,b,c){if(b===c)return a;if(void 0===c.M)return null;a=Na(a,b,c.M);return null===a?null:c.ka(a)}var Oa={},P=[];function Pa(){for(;P.length;){var a=P.pop();a.I.X=!1;a["delete"]()}}var Q=void 0,R={};function Qa(a,b){for(void 0===b&&L("ptr should not be undefined");a.M;)b=a.Z(b),a=a.M;return R[b]}
function Ra(a,b){b.L&&b.K||Ia("makeClassHandle requires ptr and ptrType");!!b.P!==!!b.O&&Ia("Both smartPtrType and smartPtr must be specified");b.count={value:1};return S(Object.create(a,{I:{value:b}}))}function S(a){if("undefined"===typeof FinalizationRegistry)return S=b=>b,a;Ka=new FinalizationRegistry(b=>{Ma(b.I)});S=b=>{var c=b.I;c.O&&Ka.register(b,{I:c},b);return b};La=b=>{Ka.unregister(b)};return S(a)}function T(){}
function Sa(a,b,c){if(void 0===a[b].N){var d=a[b];a[b]=function(){a[b].N.hasOwnProperty(arguments.length)||L(`Function '${c}' called with an invalid number of arguments (${arguments.length}) - expects one of (${a[b].N})!`);return a[b].N[arguments.length].apply(this,arguments)};a[b].N=[];a[b].N[d.W]=d}}
function Ta(a,b){Module.hasOwnProperty(a)?(L(`Cannot register public name '${a}' twice`),Sa(Module,a,a),Module.hasOwnProperty(void 0)&&L("Cannot register multiple overloads of a function with the same number of arguments (undefined)!"),Module[a].N[void 0]=b):Module[a]=b}function Ua(a,b,c,d,e,g,h,f){this.name=a;this.constructor=b;this.T=c;this.V=d;this.M=e;this.la=g;this.Z=h;this.ka=f;this.pa=[]}
function Va(a,b,c){for(;b!==c;)b.Z||L(`Expected null or instance of ${c.name}, got an instance of ${b.name}`),a=b.Z(a),b=b.M;return a}function Wa(a,b){if(null===b)return this.ca&&L(`null is not a valid ${this.name}`),0;b.I||L(`Cannot pass "${Xa(b)}" as a ${this.name}`);b.I.K||L(`Cannot pass deleted object as a pointer of type ${this.name}`);return Va(b.I.K,b.I.L.J,this.J)}
function Ya(a,b){if(null===b){this.ca&&L(`null is not a valid ${this.name}`);if(this.ba){var c=this.qa();null!==a&&a.push(this.V,c);return c}return 0}b.I||L(`Cannot pass "${Xa(b)}" as a ${this.name}`);b.I.K||L(`Cannot pass deleted object as a pointer of type ${this.name}`);!this.aa&&b.I.L.aa&&L(`Cannot convert argument of type ${b.I.P?b.I.P.name:b.I.L.name} to parameter type ${this.name}`);c=Va(b.I.K,b.I.L.J,this.J);if(this.ba)switch(void 0===b.I.O&&L("Passing raw pointer to smart pointer is illegal"),
this.ta){case 0:b.I.P===this?c=b.I.O:L(`Cannot convert argument of type ${b.I.P?b.I.P.name:b.I.L.name} to parameter type ${this.name}`);break;case 1:c=b.I.O;break;case 2:if(b.I.P===this)c=b.I.O;else{var d=b.clone();c=this.ra(c,U(function(){d["delete"]()}));null!==a&&a.push(this.V,c)}break;default:L("Unsupporting sharing policy")}return c}
function Za(a,b){if(null===b)return this.ca&&L(`null is not a valid ${this.name}`),0;b.I||L(`Cannot pass "${Xa(b)}" as a ${this.name}`);b.I.K||L(`Cannot pass deleted object as a pointer of type ${this.name}`);b.I.L.aa&&L(`Cannot convert argument of type ${b.I.L.name} to parameter type ${this.name}`);return Va(b.I.K,b.I.L.J,this.J)}function $a(a){return this.fromWireType(B[a>>2])}
function V(a,b,c,d){this.name=a;this.J=b;this.ca=c;this.aa=d;this.ba=!1;this.V=this.ra=this.qa=this.ga=this.ta=this.oa=void 0;void 0!==b.M?this.toWireType=Ya:(this.toWireType=d?Wa:Za,this.S=null)}function ab(a,b){Module.hasOwnProperty(a)||Ia("Replacing nonexistant public symbol");Module[a]=b;Module[a].W=void 0}
function bb(a,b){var c=[];return function(){c.length=0;Object.assign(c,arguments);if(a.includes("j")){var d=Module["dynCall_"+a];d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)}else d=ma.get(b).apply(null,c);return d}}function W(a,b){a=H(a);var c=a.includes("j")?bb(a,b):ma.get(b);"function"!=typeof c&&L(`unknown function pointer with signature ${a}: ${b}`);return c}var cb=void 0;function db(a){a=eb(a);var b=H(a);X(a);return b}
function Y(a,b){function c(g){e[g]||J[g]||(Da[g]?Da[g].forEach(c):(d.push(g),e[g]=!0))}var d=[],e={};b.forEach(c);throw new cb(`${a}: `+d.map(db).join([", "]));}function fb(a){for(;a.length;){var b=a.pop();a.pop()(b)}}
function gb(a,b,c,d,e){var g=b.length;2>g&&L("argTypes array size mismatch! Must at least get return value and 'this' types!");var h=null!==b[1]&&null!==c,f=!1;for(c=1;c<b.length;++c)if(null!==b[c]&&void 0===b[c].S){f=!0;break}var k="void"!==b[0].name,m=g-2,l=Array(m),n=[],q=[];return function(){arguments.length!==m&&L(`function ${a} called with ${arguments.length} arguments, expected ${m} args!`);q.length=0;n.length=h?2:1;n[0]=e;if(h){var t=b[1].toWireType(q,this);n[1]=t}for(var r=0;r<m;++r)l[r]=
b[r+2].toWireType(q,arguments[r]),n.push(l[r]);r=d.apply(null,n);if(f)fb(q);else for(var v=h?1:2;v<b.length;v++){var G=1===v?t:l[v-2];null!==b[v].S&&b[v].S(G)}t=k?b[0].fromWireType(r):void 0;return t}}function hb(a,b){for(var c=[],d=0;d<a;d++)c.push(C[b+4*d>>2]);return c}
function ib(a,b,c){a instanceof Object||L(`${c} with invalid "this": ${a}`);a instanceof b.J.constructor||L(`${c} incompatible with "this" of type ${a.constructor.name}`);a.I.K||L(`cannot call emscripten binding method ${c} on deleted object`);return Va(a.I.K,a.I.L.J,b.J)}
var Z=new function(){this.R=[void 0];this.da=[];this.get=function(a){return this.R[a]};this.has=function(a){return void 0!==this.R[a]};this.ha=function(a){var b=this.da.pop()||this.R.length;this.R[b]=a;return b};this.ia=function(a){this.R[a]=void 0;this.da.push(a)}};function kb(a){a>=Z.ea&&0===--Z.get(a).sa&&Z.ia(a)}
var lb=a=>{a||L("Cannot use deleted val. handle = "+a);return Z.get(a).value},U=a=>{switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:return Z.ha({sa:1,value:a})}};function Xa(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function mb(a,b){switch(b){case 2:return function(c){return this.fromWireType(ja[c>>2])};case 3:return function(c){return this.fromWireType(ka[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function nb(a,b,c){switch(b){case 0:return c?function(d){return ha[d]}:function(d){return z[d]};case 1:return c?function(d){return A[d>>1]}:function(d){return ia[d>>1]};case 2:return c?function(d){return B[d>>2]}:function(d){return C[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}var ob="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ya(a,b){var c=z,d=a+b;for(b=a;c[b]&&!(b>=d);)++b;if(16<b-a&&c.buffer&&ob)return ob.decode(c.subarray(a,b));for(d="";a<b;){var e=c[a++];if(e&128){var g=c[a++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var h=c[a++]&63;e=224==(e&240)?(e&15)<<12|g<<6|h:(e&7)<<18|g<<12|h<<6|c[a++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}
var pb="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0;function qb(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&ia[c];)++c;c<<=1;if(32<c-a&&pb)return pb.decode(z.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=A[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c}function rb(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)A[b>>1]=a.charCodeAt(e),b+=2;A[b>>1]=0;return b-d}function sb(a){return 2*a.length}
function tb(a,b){for(var c=0,d="";!(c>=b/4);){var e=B[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}function ub(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var g=a.charCodeAt(e);if(55296<=g&&57343>=g){var h=a.charCodeAt(++e);g=65536+((g&1023)<<10)|h&1023}B[b>>2]=g;b+=4;if(b+4>c)break}B[b>>2]=0;return b-d}
function vb(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}function wb(a,b){var c=J[a];void 0===c&&L(b+" has unknown type "+db(a));return c}var xb={},yb=[];function zb(){var a=Module.SpineWasmUtil,b=a.getCurrentListenerID(),c=a.getCurrentTrackEntry(),d=a.getCurrentEvent();a=a.getCurrentEventType();globalThis.TrackEntryListeners.emitListener(b,c,d,a)}Module._spineListenerCallBackFromJS=zb;
function Ab(){var a=Module.SpineWasmUtil,b=a.getCurrentListenerID(),c=a.getCurrentEventType(),d=a.getCurrentTrackEntry();a=a.getCurrentEvent();globalThis.TrackEntryListeners.emitTrackEntryListener(b,d,a,c)}Module._spineTrackListenerCallback=Ab;for(var Bb=Array(256),Cb=0;256>Cb;++Cb)Bb[Cb]=String.fromCharCode(Cb);Ca=Bb;K=Module.BindingError=Ga("BindingError");Ha=Module.InternalError=Ga("InternalError");
T.prototype.isAliasOf=function(a){if(!(this instanceof T&&a instanceof T))return!1;var b=this.I.L.J,c=this.I.K,d=a.I.L.J;for(a=a.I.K;b.M;)c=b.Z(c),b=b.M;for(;d.M;)a=d.Z(a),d=d.M;return b===d&&c===a};T.prototype.clone=function(){this.I.K||Ja(this);if(this.I.Y)return this.I.count.value+=1,this;var a=S,b=Object,c=b.create,d=Object.getPrototypeOf(this),e=this.I;a=a(c.call(b,d,{I:{value:{count:e.count,X:e.X,Y:e.Y,K:e.K,L:e.L,O:e.O,P:e.P}}}));a.I.count.value+=1;a.I.X=!1;return a};
T.prototype["delete"]=function(){this.I.K||Ja(this);this.I.X&&!this.I.Y&&L("Object already scheduled for deletion");La(this);Ma(this.I);this.I.Y||(this.I.O=void 0,this.I.K=void 0)};T.prototype.isDeleted=function(){return!this.I.K};T.prototype.deleteLater=function(){this.I.K||Ja(this);this.I.X&&!this.I.Y&&L("Object already scheduled for deletion");P.push(this);1===P.length&&Q&&Q(Pa);this.I.X=!0;return this};Module.getInheritedInstanceCount=function(){return Object.keys(R).length};
Module.getLiveInheritedInstances=function(){var a=[],b;for(b in R)R.hasOwnProperty(b)&&a.push(R[b]);return a};Module.flushPendingDeletes=Pa;Module.setDelayFunction=function(a){Q=a;P.length&&Q&&Q(Pa)};V.prototype.ma=function(a){this.ga&&(a=this.ga(a));return a};V.prototype.fa=function(a){this.V&&this.V(a)};V.prototype.argPackAdvance=8;V.prototype.readValueFromPointer=$a;V.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
V.prototype.fromWireType=function(a){function b(){return this.ba?Ra(this.J.T,{L:this.oa,K:c,P:this,O:a}):Ra(this.J.T,{L:this,K:a})}var c=this.ma(a);if(!c)return this.fa(a),null;var d=Qa(this.J,c);if(void 0!==d){if(0===d.I.count.value)return d.I.K=c,d.I.O=a,d.clone();d=d.clone();this.fa(a);return d}d=this.J.la(c);d=Oa[d];if(!d)return b.call(this);d=this.aa?d.ja:d.pointerType;var e=Na(c,this.J,d.J);return null===e?b.call(this):this.ba?Ra(d.J.T,{L:d,K:e,P:this,O:a}):Ra(d.J.T,{L:d,K:e})};
cb=Module.UnboundTypeError=Ga("UnboundTypeError");Z.R.push({value:void 0},{value:null},{value:!0},{value:!1});Z.ea=Z.R.length;Module.count_emval_handles=function(){for(var a=0,b=Z.ea;b<Z.R.length;++b)void 0!==Z.R[b]&&++a;return a};
var Eb={v:function(){},z:function(a,b,c,d,e){var g=Ba(c);b=H(b);O(a,{name:b,fromWireType:function(h){return!!h},toWireType:function(h,f){return f?d:e},argPackAdvance:8,readValueFromPointer:function(h){if(1===c)var f=ha;else if(2===c)f=A;else if(4===c)f=B;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(f[h>>g])},S:null})},c:function(a,b,c,d,e,g,h,f,k,m,l,n,q){l=H(l);g=W(e,g);f&&(f=W(h,f));m&&(m=W(k,m));q=W(n,q);var t=Ea(l);Ta(t,function(){Y(`Cannot construct ${l} due to unbound types`,
[d])});N([a,b,c],d?[d]:[],function(r){r=r[0];if(d){var v=r.J;var G=v.T}else G=T.prototype;r=Fa(t,function(){if(Object.getPrototypeOf(this)!==M)throw new K("Use 'new' to construct "+l);if(void 0===x.U)throw new K(l+" has no accessible constructor");var jb=x.U[arguments.length];if(void 0===jb)throw new K(`Tried to invoke ctor of ${l} with invalid number of parameters (${arguments.length}) - expected (${Object.keys(x.U).toString()}) parameters instead!`);return jb.apply(this,arguments)});var M=Object.create(G,
{constructor:{value:r}});r.prototype=M;var x=new Ua(l,r,M,q,v,g,f,m);x.M&&(void 0===x.M.$&&(x.M.$=[]),x.M.$.push(x));v=new V(l,x,!0,!1);G=new V(l+"*",x,!1,!1);var ba=new V(l+" const*",x,!1,!0);Oa[a]={pointerType:G,ja:ba};ab(t,r);return[v,G,ba]})},h:function(a,b,c,d,e,g,h){var f=hb(c,d);b=H(b);g=W(e,g);N([],[a],function(k){function m(){Y(`Cannot call ${l} due to unbound types`,f)}k=k[0];var l=`${k.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);var n=k.J.constructor;void 0===n[b]?(m.W=c-
1,n[b]=m):(Sa(n,b,l),n[b].N[c-1]=m);N([],f,function(q){q=gb(l,[q[0],null].concat(q.slice(1)),null,g,h);void 0===n[b].N?(q.W=c-1,n[b]=q):n[b].N[c-1]=q;if(k.J.$)for(const t of k.J.$)t.constructor.hasOwnProperty(b)||(t.constructor[b]=q);return[]});return[]})},k:function(a,b,c,d,e,g,h,f){b=H(b);g=W(e,g);N([],[a],function(k){k=k[0];var m=`${k.name}.${b}`,l={get:function(){Y(`Cannot access ${m} due to unbound types`,[c])},enumerable:!0,configurable:!0};l.set=f?()=>{Y(`Cannot access ${m} due to unbound types`,
[c])}:()=>{L(`${m} is a read-only property`)};Object.defineProperty(k.J.constructor,b,l);N([],[c],function(n){n=n[0];var q={get:function(){return n.fromWireType(g(d))},enumerable:!0};f&&(f=W(h,f),q.set=t=>{var r=[];f(d,n.toWireType(r,t));fb(r)});Object.defineProperty(k.J.constructor,b,q);return[]});return[]})},d:function(a,b,c,d,e,g){0<b||y();var h=hb(b,c);e=W(d,e);N([],[a],function(f){f=f[0];var k=`constructor ${f.name}`;void 0===f.J.U&&(f.J.U=[]);if(void 0!==f.J.U[b-1])throw new K(`Cannot register multiple constructors with identical number of parameters (${b-
1}) for class '${f.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);f.J.U[b-1]=()=>{Y(`Cannot construct ${f.name} due to unbound types`,h)};N([],h,function(m){m.splice(1,0,null);f.J.U[b-1]=gb(k,m,null,e,g);return[]});return[]})},a:function(a,b,c,d,e,g,h,f){var k=hb(c,d);b=H(b);g=W(e,g);N([],[a],function(m){function l(){Y(`Cannot call ${n} due to unbound types`,k)}m=m[0];var n=`${m.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);
f&&m.J.pa.push(b);var q=m.J.T,t=q[b];void 0===t||void 0===t.N&&t.className!==m.name&&t.W===c-2?(l.W=c-2,l.className=m.name,q[b]=l):(Sa(q,b,n),q[b].N[c-2]=l);N([],k,function(r){r=gb(n,r,m,g,h);void 0===q[b].N?(r.W=c-2,q[b]=r):q[b].N[c-2]=r;return[]});return[]})},b:function(a,b,c,d,e,g,h,f,k,m){b=H(b);e=W(d,e);N([],[a],function(l){l=l[0];var n=`${l.name}.${b}`,q={get:function(){Y(`Cannot access ${n} due to unbound types`,[c,h])},enumerable:!0,configurable:!0};q.set=k?()=>{Y(`Cannot access ${n} due to unbound types`,
[c,h])}:()=>{L(n+" is a read-only property")};Object.defineProperty(l.J.T,b,q);N([],k?[c,h]:[c],function(t){var r=t[0],v={get:function(){var M=ib(this,l,n+" getter");return r.fromWireType(e(g,M))},enumerable:!0};if(k){k=W(f,k);var G=t[1];v.set=function(M){var x=ib(this,l,n+" setter"),ba=[];k(m,x,G.toWireType(ba,M));fb(ba)}}Object.defineProperty(l.J.T,b,v);return[]});return[]})},y:function(a,b){b=H(b);O(a,{name:b,fromWireType:function(c){var d=lb(c);kb(c);return d},toWireType:function(c,d){return U(d)},
argPackAdvance:8,readValueFromPointer:$a,S:null})},s:function(a,b,c){c=Ba(c);b=H(b);O(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,e){return e},argPackAdvance:8,readValueFromPointer:mb(b,c),S:null})},f:function(a,b,c,d,e){b=H(b);-1===e&&(e=4294967295);e=Ba(c);var g=f=>f;if(0===d){var h=32-8*c;g=f=>f<<h>>>h}c=b.includes("unsigned")?function(f,k){return k>>>0}:function(f,k){return k};O(a,{name:b,fromWireType:g,toWireType:c,argPackAdvance:8,readValueFromPointer:nb(b,e,0!==d),S:null})},
g:function(a,b,c){function d(g){g>>=2;var h=C;return new e(h.buffer,h[g+1],h[g])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=H(c);O(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{na:!0})},p:function(a,b){b=H(b);var c="std::string"===b;O(a,{name:b,fromWireType:function(d){var e=C[d>>2],g=d+4;if(c)for(var h=g,f=0;f<=e;++f){var k=g+f;if(f==e||0==z[k]){h=h?ya(h,k-h):"";if(void 0===m)var m=h;else m+=String.fromCharCode(0),
m+=h;h=k+1}}else{m=Array(e);for(f=0;f<e;++f)m[f]=String.fromCharCode(z[g+f]);m=m.join("")}X(d);return m},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var g,h="string"==typeof e;h||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array||L("Cannot pass non-string to std::string");var f;if(c&&h)for(g=f=0;g<e.length;++g){var k=e.charCodeAt(g);127>=k?f++:2047>=k?f+=2:55296<=k&&57343>=k?(f+=4,++g):f+=3}else f=e.length;g=f;f=Db(4+g+1);k=f+4;C[f>>2]=g;
if(c&&h){if(h=k,k=g+1,g=z,0<k){k=h+k-1;for(var m=0;m<e.length;++m){var l=e.charCodeAt(m);if(55296<=l&&57343>=l){var n=e.charCodeAt(++m);l=65536+((l&1023)<<10)|n&1023}if(127>=l){if(h>=k)break;g[h++]=l}else{if(2047>=l){if(h+1>=k)break;g[h++]=192|l>>6}else{if(65535>=l){if(h+2>=k)break;g[h++]=224|l>>12}else{if(h+3>=k)break;g[h++]=240|l>>18;g[h++]=128|l>>12&63}g[h++]=128|l>>6&63}g[h++]=128|l&63}}g[h]=0}}else if(h)for(h=0;h<g;++h)m=e.charCodeAt(h),255<m&&(X(k),L("String has UTF-16 code units that do not fit in 8 bits")),
z[k+h]=m;else for(h=0;h<g;++h)z[k+h]=e[h];null!==d&&d.push(X,f);return f},argPackAdvance:8,readValueFromPointer:$a,S:function(d){X(d)}})},o:function(a,b,c){c=H(c);if(2===b){var d=qb;var e=rb;var g=sb;var h=()=>ia;var f=1}else 4===b&&(d=tb,e=ub,g=vb,h=()=>C,f=2);O(a,{name:c,fromWireType:function(k){for(var m=C[k>>2],l=h(),n,q=k+4,t=0;t<=m;++t){var r=k+4+t*b;if(t==m||0==l[r>>f])q=d(q,r-q),void 0===n?n=q:(n+=String.fromCharCode(0),n+=q),q=r+b}X(k);return n},toWireType:function(k,m){"string"!=typeof m&&
L(`Cannot pass non-string to C++ string type ${c}`);var l=g(m),n=Db(4+l+b);C[n>>2]=l>>f;e(m,n+4,l+b);null!==k&&k.push(X,n);return n},argPackAdvance:8,readValueFromPointer:$a,S:function(k){X(k)}})},x:function(a,b){b=H(b);O(a,{ua:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},j:function(a,b,c){a=lb(a);b=wb(b,"emval::as");var d=[],e=U(d);C[c>>2]=e;return b.toWireType(d,a)},e:kb,l:function(a,b){a=lb(a);b=lb(b);return U(a[b])},m:function(a){var b=xb[a];return U(void 0===
b?H(a):b)},i:function(a){var b=lb(a);fb(b);kb(a)},r:function(a,b){a=wb(a,"_emval_take_value");a=a.readValueFromPointer(b);return U(a)},q:function(){y("")},n:function(a,b,c){yb.length=0;var d;for(c>>=2;d=z[b++];)c+=105!=d&c,yb.push(105==d?B[c]:ka[c++>>1]),++c;return za[a].apply(null,yb)},w:function(a){var b=z.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,d);a:{e=e.min.call(e,2147483648,d+(65536-d%65536)%65536)-ea.buffer.byteLength+
65535>>>16;try{ea.grow(e);la();var g=1;break a}catch(h){}g=void 0}if(g)return!0}return!1},u:zb,t:Ab};
(function(){function a(c){c=c.exports;Module.asm=c;ea=Module.asm.A;la();ma=Module.asm.C;oa.unshift(Module.asm.B);D--;Module.monitorRunDependencies&&Module.monitorRunDependencies(D);if(0==D&&(null!==ra&&(clearInterval(ra),ra=null),E)){var d=E;E=null;d()}return c}var b={a:Eb};D++;Module.monitorRunDependencies&&Module.monitorRunDependencies(D);if(Module.instantiateWasm)try{return Module.instantiateWasm(b,a)}catch(c){u("Module.instantiateWasm callback failed with error: "+c),ca(c)}xa(b,function(c){a(c.instance)}).catch(ca);
return{}})();function Db(){return(Db=Module.asm.D).apply(null,arguments)}function X(){return(X=Module.asm.E).apply(null,arguments)}function eb(){return(eb=Module.asm.F).apply(null,arguments)}Module.__embind_initialize_bindings=function(){return(Module.__embind_initialize_bindings=Module.asm.G).apply(null,arguments)};Module._sbrk=function(){return(Module._sbrk=Module.asm.H).apply(null,arguments)};Module.___heap_base=89344;var Fb;E=function Gb(){Fb||Hb();Fb||(E=Gb)};
function Hb(){function a(){if(!Fb&&(Fb=!0,Module.calledRun=!0,!fa)){Aa(oa);aa(Module);if(Module.onRuntimeInitialized)Module.onRuntimeInitialized();if(Module.postRun)for("function"==typeof Module.postRun&&(Module.postRun=[Module.postRun]);Module.postRun.length;){var b=Module.postRun.shift();pa.unshift(b)}Aa(pa)}}if(!(0<D)){if(Module.preRun)for("function"==typeof Module.preRun&&(Module.preRun=[Module.preRun]);Module.preRun.length;)qa();Aa(na);0<D||(Module.setStatus?(Module.setStatus("Running..."),setTimeout(function(){setTimeout(function(){Module.setStatus("")},
1);a()},1)):a())}}if(Module.preInit)for("function"==typeof Module.preInit&&(Module.preInit=[Module.preInit]);0<Module.preInit.length;)Module.preInit.pop()();Hb();function getSpineMemoryInfo(){const a=Module._sbrk?Module._sbrk(0):0,b=Module.HEAP8?Module.HEAP8.length:0;return{heapUsed:a,heapTotal:b,heapFree:b-a,get heapUsedMB(){return(this.heapUsed/1024/1024).toFixed(2)},get heapTotalMB(){return(this.heapTotal/1024/1024).toFixed(2)},get heapFreeMB(){return(this.heapFree/1024/1024).toFixed(2)}}}
"undefined"!==typeof globalThis&&(globalThis.getSpineMemoryInfo=getSpineMemoryInfo);"undefined"!==typeof Module&&(Module.getSpineMemoryInfo=getSpineMemoryInfo);console.log("[Spine] getSpineMemoryInfo \u5df2\u6ce8\u518c");


  return spineWasm.ready
}

);
})();
export default spineWasm;