
var spineWasm = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  
  return (
function(spineWasm = {})  {

var f;f||(f=typeof spineWasm !== 'undefined' ? spineWasm : {});var aa,ba;f.ready=new Promise((a,b)=>{aa=a;ba=b});var da=Object.assign({},f),q="";"undefined"!=typeof document&&document.currentScript&&(q=document.currentScript.src);_scriptDir&&(q=_scriptDir);0!==q.indexOf("blob:")?q=q.substr(0,q.replace(/[?#].*/,"").lastIndexOf("/")+1):q="";var v=f.printErr||console.error.bind(console);Object.assign(f,da);da=null;var x;f.wasmBinary&&(x=f.wasmBinary);var noExitRuntime=f.noExitRuntime||!0;
"object"!=typeof WebAssembly&&z("no native wasm support detected");var ea,fa=!1,ha,A,B,ia,C,D,ja,ka;function la(){var a=ea.buffer;f.HEAP8=ha=new Int8Array(a);f.HEAP16=B=new Int16Array(a);f.HEAP32=C=new Int32Array(a);f.HEAPU8=A=new Uint8Array(a);f.HEAPU16=ia=new Uint16Array(a);f.HEAPU32=D=new Uint32Array(a);f.HEAPF32=ja=new Float32Array(a);f.HEAPF64=ka=new Float64Array(a)}var ma,na=[],oa=[],pa=[];function qa(){var a=f.preRun.shift();na.unshift(a)}var E=0,ra=null,F=null;
function z(a){if(f.onAbort)f.onAbort(a);a="Aborted("+a+")";v(a);fa=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ba(a);throw a;}function sa(a){return a.startsWith("data:application/octet-stream;base64,")}var G;G="spine.wasm";if(!sa(G)){var ta=G;G=f.locateFile?f.locateFile(ta,q):q+ta}function ua(a){try{if(a==G&&x)return new Uint8Array(x);throw"both async and sync fetching of the wasm failed";}catch(b){z(b)}}
function va(a){return x||"function"!=typeof fetch?Promise.resolve().then(()=>ua(a)):fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>ua(a))}function wa(a,b,c){return va(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{v("failed to asynchronously prepare wasm: "+d);z(d)})}
function xa(a,b){var c=G;return x||"function"!=typeof WebAssembly.instantiateStreaming||sa(c)||"function"!=typeof fetch?wa(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){v("wasm streaming compile failed: "+e);v("falling back to ArrayBuffer instantiation");return wa(c,a,b)}))}var za={22280:a=>{console.warn("[Spine]",a?ya(a):"")}};function Aa(a){for(;0<a.length;)a.shift()(f)}
function Ba(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError(`Unknown type size: ${a}`);}}var Ca=void 0;function I(a){for(var b="";A[a];)b+=Ca[A[a++]];return b}var J={},K={},Da={};function Ea(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a}function Fa(a,b){a=Ea(a);return{[a]:function(){return b.apply(this,arguments)}}[a]}
function Ga(a){var b=Error,c=Fa(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:`${this.name}: ${this.message}`};return c}var L=void 0;function M(a){throw new L(a);}var Ha=void 0;function Ia(a){throw new Ha(a);}
function O(a,b,c){function d(g){g=c(g);g.length!==a.length&&Ia("Mismatched type converter count");for(var l=0;l<a.length;++l)P(a[l],g[l])}a.forEach(function(g){Da[g]=b});var e=Array(b.length),h=[],k=0;b.forEach((g,l)=>{K.hasOwnProperty(g)?e[l]=K[g]:(h.push(g),J.hasOwnProperty(g)||(J[g]=[]),J[g].push(()=>{e[l]=K[g];++k;k===h.length&&d(e)}))});0===h.length&&d(e)}
function P(a,b,c={}){if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||M(`type "${d}" must have a positive integer typeid pointer`);if(K.hasOwnProperty(a)){if(c.sa)return;M(`Cannot register type '${d}' twice`)}K[a]=b;delete Da[a];J.hasOwnProperty(a)&&(b=J[a],delete J[a],b.forEach(e=>e()))}function Ja(a){M(a.I.L.J.name+" instance already deleted")}var Ka=!1;function La(){}
function Ma(a){--a.count.value;0===a.count.value&&(a.O?a.P.V(a.O):a.L.J.V(a.K))}function Na(a,b,c){if(b===c)return a;if(void 0===c.M)return null;a=Na(a,b,c.M);return null===a?null:c.ma(a)}var Oa={},Q=[];function Pa(){for(;Q.length;){var a=Q.pop();a.I.X=!1;a["delete"]()}}var R=void 0,S={};function Qa(a,b){for(void 0===b&&M("ptr should not be undefined");a.M;)b=a.Z(b),a=a.M;return S[b]}
function Ra(a,b){b.L&&b.K||Ia("makeClassHandle requires ptr and ptrType");!!b.P!==!!b.O&&Ia("Both smartPtrType and smartPtr must be specified");b.count={value:1};return Sa(Object.create(a,{I:{value:b}}))}function Sa(a){if("undefined"===typeof FinalizationRegistry)return Sa=b=>b,a;Ka=new FinalizationRegistry(b=>{Ma(b.I)});Sa=b=>{var c=b.I;c.O&&Ka.register(b,{I:c},b);return b};La=b=>{Ka.unregister(b)};return Sa(a)}function T(){}
function Ta(a,b,c){if(void 0===a[b].N){var d=a[b];a[b]=function(){a[b].N.hasOwnProperty(arguments.length)||M(`Function '${c}' called with an invalid number of arguments (${arguments.length}) - expects one of (${a[b].N})!`);return a[b].N[arguments.length].apply(this,arguments)};a[b].N=[];a[b].N[d.W]=d}}
function Ua(a,b){f.hasOwnProperty(a)?(M(`Cannot register public name '${a}' twice`),Ta(f,a,a),f.hasOwnProperty(void 0)&&M("Cannot register multiple overloads of a function with the same number of arguments (undefined)!"),f[a].N[void 0]=b):f[a]=b}function Va(a,b,c,d,e,h,k,g){this.name=a;this.constructor=b;this.T=c;this.V=d;this.M=e;this.na=h;this.Z=k;this.ma=g;this.ua=[]}
function Wa(a,b,c){for(;b!==c;)b.Z||M(`Expected null or instance of ${c.name}, got an instance of ${b.name}`),a=b.Z(a),b=b.M;return a}function Xa(a,b){if(null===b)return this.ca&&M(`null is not a valid ${this.name}`),0;b.I||M(`Cannot pass "${Ya(b)}" as a ${this.name}`);b.I.K||M(`Cannot pass deleted object as a pointer of type ${this.name}`);return Wa(b.I.K,b.I.L.J,this.J)}
function Za(a,b){if(null===b){this.ca&&M(`null is not a valid ${this.name}`);if(this.ba){var c=this.va();null!==a&&a.push(this.V,c);return c}return 0}b.I||M(`Cannot pass "${Ya(b)}" as a ${this.name}`);b.I.K||M(`Cannot pass deleted object as a pointer of type ${this.name}`);!this.aa&&b.I.L.aa&&M(`Cannot convert argument of type ${b.I.P?b.I.P.name:b.I.L.name} to parameter type ${this.name}`);c=Wa(b.I.K,b.I.L.J,this.J);if(this.ba)switch(void 0===b.I.O&&M("Passing raw pointer to smart pointer is illegal"),
this.ya){case 0:b.I.P===this?c=b.I.O:M(`Cannot convert argument of type ${b.I.P?b.I.P.name:b.I.L.name} to parameter type ${this.name}`);break;case 1:c=b.I.O;break;case 2:if(b.I.P===this)c=b.I.O;else{var d=b.clone();c=this.wa(c,U(function(){d["delete"]()}));null!==a&&a.push(this.V,c)}break;default:M("Unsupporting sharing policy")}return c}
function $a(a,b){if(null===b)return this.ca&&M(`null is not a valid ${this.name}`),0;b.I||M(`Cannot pass "${Ya(b)}" as a ${this.name}`);b.I.K||M(`Cannot pass deleted object as a pointer of type ${this.name}`);b.I.L.aa&&M(`Cannot convert argument of type ${b.I.L.name} to parameter type ${this.name}`);return Wa(b.I.K,b.I.L.J,this.J)}function ab(a){return this.fromWireType(C[a>>2])}
function V(a,b,c,d){this.name=a;this.J=b;this.ca=c;this.aa=d;this.ba=!1;this.V=this.wa=this.va=this.ga=this.ya=this.ta=void 0;void 0!==b.M?this.toWireType=Za:(this.toWireType=d?Xa:$a,this.S=null)}function bb(a,b){f.hasOwnProperty(a)||Ia("Replacing nonexistant public symbol");f[a]=b;f[a].W=void 0}
function cb(a,b){var c=[];return function(){c.length=0;Object.assign(c,arguments);if(a.includes("j")){var d=f["dynCall_"+a];d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)}else d=ma.get(b).apply(null,c);return d}}function W(a,b){a=I(a);var c=a.includes("j")?cb(a,b):ma.get(b);"function"!=typeof c&&M(`unknown function pointer with signature ${a}: ${b}`);return c}var db=void 0;function eb(a){a=fb(a);var b=I(a);X(a);return b}
function Y(a,b){function c(h){e[h]||K[h]||(Da[h]?Da[h].forEach(c):(d.push(h),e[h]=!0))}var d=[],e={};b.forEach(c);throw new db(`${a}: `+d.map(eb).join([", "]));}function gb(a){for(;a.length;){var b=a.pop();a.pop()(b)}}
function hb(a,b,c,d,e){var h=b.length;2>h&&M("argTypes array size mismatch! Must at least get return value and 'this' types!");var k=null!==b[1]&&null!==c,g=!1;for(c=1;c<b.length;++c)if(null!==b[c]&&void 0===b[c].S){g=!0;break}var l="void"!==b[0].name,n=h-2,m=Array(n),p=[],r=[];return function(){arguments.length!==n&&M(`function ${a} called with ${arguments.length} arguments, expected ${n} args!`);r.length=0;p.length=k?2:1;p[0]=e;if(k){var u=b[1].toWireType(r,this);p[1]=u}for(var t=0;t<n;++t)m[t]=
b[t+2].toWireType(r,arguments[t]),p.push(m[t]);t=d.apply(null,p);if(g)gb(r);else for(var w=k?1:2;w<b.length;w++){var H=1===w?u:m[w-2];null!==b[w].S&&b[w].S(H)}u=l?b[0].fromWireType(t):void 0;return u}}function ib(a,b){for(var c=[],d=0;d<a;d++)c.push(D[b+4*d>>2]);return c}
function jb(a,b,c){a instanceof Object||M(`${c} with invalid "this": ${a}`);a instanceof b.J.constructor||M(`${c} incompatible with "this" of type ${a.constructor.name}`);a.I.K||M(`cannot call emscripten binding method ${c} on deleted object`);return Wa(a.I.K,a.I.L.J,b.J)}
var Z=new function(){this.R=[void 0];this.da=[];this.get=function(a){return this.R[a]};this.has=function(a){return void 0!==this.R[a]};this.ia=function(a){var b=this.da.pop()||this.R.length;this.R[b]=a;return b};this.ja=function(a){this.R[a]=void 0;this.da.push(a)}};function lb(a){a>=Z.ea&&0===--Z.get(a).xa&&Z.ja(a)}
var mb=a=>{a||M("Cannot use deleted val. handle = "+a);return Z.get(a).value},U=a=>{switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:return Z.ia({xa:1,value:a})}};function Ya(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function nb(a,b){switch(b){case 2:return function(c){return this.fromWireType(ja[c>>2])};case 3:return function(c){return this.fromWireType(ka[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function ob(a,b,c){switch(b){case 0:return c?function(d){return ha[d]}:function(d){return A[d]};case 1:return c?function(d){return B[d>>1]}:function(d){return ia[d>>1]};case 2:return c?function(d){return C[d>>2]}:function(d){return D[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}var pb="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ya(a,b){var c=A,d=a+b;for(b=a;c[b]&&!(b>=d);)++b;if(16<b-a&&c.buffer&&pb)return pb.decode(c.subarray(a,b));for(d="";a<b;){var e=c[a++];if(e&128){var h=c[a++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|h);else{var k=c[a++]&63;e=224==(e&240)?(e&15)<<12|h<<6|k:(e&7)<<18|h<<12|k<<6|c[a++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}
var qb="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0;function rb(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&ia[c];)++c;c<<=1;if(32<c-a&&qb)return qb.decode(A.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=B[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c}function sb(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)B[b>>1]=a.charCodeAt(e),b+=2;B[b>>1]=0;return b-d}function tb(a){return 2*a.length}
function ub(a,b){for(var c=0,d="";!(c>=b/4);){var e=C[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}function vb(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var h=a.charCodeAt(e);if(55296<=h&&57343>=h){var k=a.charCodeAt(++e);h=65536+((h&1023)<<10)|k&1023}C[b>>2]=h;b+=4;if(b+4>c)break}C[b>>2]=0;return b-d}
function wb(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}function xb(a,b){var c=K[a];void 0===c&&M(b+" has unknown type "+eb(a));return c}var yb={},zb=[];function Ab(){var a=f.SpineWasmUtil,b=a.getCurrentListenerID(),c=a.getCurrentTrackEntry(),d=a.getCurrentEvent();a=a.getCurrentEventType();globalThis.TrackEntryListeners.emitListener(b,c,d,a)}f._spineListenerCallBackFromJS=Ab;
function Bb(){var a=f.SpineWasmUtil,b=a.getCurrentListenerID(),c=a.getCurrentEventType(),d=a.getCurrentTrackEntry();a=a.getCurrentEvent();globalThis.TrackEntryListeners.emitTrackEntryListener(b,d,a,c)}f._spineTrackListenerCallback=Bb;for(var Cb=Array(256),Db=0;256>Db;++Db)Cb[Db]=String.fromCharCode(Db);Ca=Cb;L=f.BindingError=Ga("BindingError");Ha=f.InternalError=Ga("InternalError");
T.prototype.isAliasOf=function(a){if(!(this instanceof T&&a instanceof T))return!1;var b=this.I.L.J,c=this.I.K,d=a.I.L.J;for(a=a.I.K;b.M;)c=b.Z(c),b=b.M;for(;d.M;)a=d.Z(a),d=d.M;return b===d&&c===a};T.prototype.clone=function(){this.I.K||Ja(this);if(this.I.Y)return this.I.count.value+=1,this;var a=Sa,b=Object,c=b.create,d=Object.getPrototypeOf(this),e=this.I;a=a(c.call(b,d,{I:{value:{count:e.count,X:e.X,Y:e.Y,K:e.K,L:e.L,O:e.O,P:e.P}}}));a.I.count.value+=1;a.I.X=!1;return a};
T.prototype["delete"]=function(){this.I.K||Ja(this);this.I.X&&!this.I.Y&&M("Object already scheduled for deletion");La(this);Ma(this.I);this.I.Y||(this.I.O=void 0,this.I.K=void 0)};T.prototype.isDeleted=function(){return!this.I.K};T.prototype.deleteLater=function(){this.I.K||Ja(this);this.I.X&&!this.I.Y&&M("Object already scheduled for deletion");Q.push(this);1===Q.length&&R&&R(Pa);this.I.X=!0;return this};f.getInheritedInstanceCount=function(){return Object.keys(S).length};
f.getLiveInheritedInstances=function(){var a=[],b;for(b in S)S.hasOwnProperty(b)&&a.push(S[b]);return a};f.flushPendingDeletes=Pa;f.setDelayFunction=function(a){R=a;Q.length&&R&&R(Pa)};V.prototype.oa=function(a){this.ga&&(a=this.ga(a));return a};V.prototype.fa=function(a){this.V&&this.V(a)};V.prototype.argPackAdvance=8;V.prototype.readValueFromPointer=ab;V.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
V.prototype.fromWireType=function(a){function b(){return this.ba?Ra(this.J.T,{L:this.ta,K:c,P:this,O:a}):Ra(this.J.T,{L:this,K:a})}var c=this.oa(a);if(!c)return this.fa(a),null;var d=Qa(this.J,c);if(void 0!==d){if(0===d.I.count.value)return d.I.K=c,d.I.O=a,d.clone();d=d.clone();this.fa(a);return d}d=this.J.na(c);d=Oa[d];if(!d)return b.call(this);d=this.aa?d.la:d.pointerType;var e=Na(c,this.J,d.J);return null===e?b.call(this):this.ba?Ra(d.J.T,{L:d,K:e,P:this,O:a}):Ra(d.J.T,{L:d,K:e})};
db=f.UnboundTypeError=Ga("UnboundTypeError");Z.R.push({value:void 0},{value:null},{value:!0},{value:!1});Z.ea=Z.R.length;f.count_emval_handles=function(){for(var a=0,b=Z.ea;b<Z.R.length;++b)void 0!==Z.R[b]&&++a;return a};
var Fb={v:function(){},z:function(a,b,c,d,e){var h=Ba(c);b=I(b);P(a,{name:b,fromWireType:function(k){return!!k},toWireType:function(k,g){return g?d:e},argPackAdvance:8,readValueFromPointer:function(k){if(1===c)var g=ha;else if(2===c)g=B;else if(4===c)g=C;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(g[k>>h])},S:null})},c:function(a,b,c,d,e,h,k,g,l,n,m,p,r){m=I(m);h=W(e,h);g&&(g=W(k,g));n&&(n=W(l,n));r=W(p,r);var u=Ea(m);Ua(u,function(){Y(`Cannot construct ${m} due to unbound types`,
[d])});O([a,b,c],d?[d]:[],function(t){t=t[0];if(d){var w=t.J;var H=w.T}else H=T.prototype;t=Fa(u,function(){if(Object.getPrototypeOf(this)!==N)throw new L("Use 'new' to construct "+m);if(void 0===y.U)throw new L(m+" has no accessible constructor");var kb=y.U[arguments.length];if(void 0===kb)throw new L(`Tried to invoke ctor of ${m} with invalid number of parameters (${arguments.length}) - expected (${Object.keys(y.U).toString()}) parameters instead!`);return kb.apply(this,arguments)});var N=Object.create(H,
{constructor:{value:t}});t.prototype=N;var y=new Va(m,t,N,r,w,h,g,n);y.M&&(void 0===y.M.$&&(y.M.$=[]),y.M.$.push(y));w=new V(m,y,!0,!1);H=new V(m+"*",y,!1,!1);var ca=new V(m+" const*",y,!1,!0);Oa[a]={pointerType:H,la:ca};bb(u,t);return[w,H,ca]})},h:function(a,b,c,d,e,h,k){var g=ib(c,d);b=I(b);h=W(e,h);O([],[a],function(l){function n(){Y(`Cannot call ${m} due to unbound types`,g)}l=l[0];var m=`${l.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);var p=l.J.constructor;void 0===p[b]?(n.W=c-
1,p[b]=n):(Ta(p,b,m),p[b].N[c-1]=n);O([],g,function(r){r=hb(m,[r[0],null].concat(r.slice(1)),null,h,k);void 0===p[b].N?(r.W=c-1,p[b]=r):p[b].N[c-1]=r;if(l.J.$)for(const u of l.J.$)u.constructor.hasOwnProperty(b)||(u.constructor[b]=r);return[]});return[]})},k:function(a,b,c,d,e,h,k,g){b=I(b);h=W(e,h);O([],[a],function(l){l=l[0];var n=`${l.name}.${b}`,m={get:function(){Y(`Cannot access ${n} due to unbound types`,[c])},enumerable:!0,configurable:!0};m.set=g?()=>{Y(`Cannot access ${n} due to unbound types`,
[c])}:()=>{M(`${n} is a read-only property`)};Object.defineProperty(l.J.constructor,b,m);O([],[c],function(p){p=p[0];var r={get:function(){return p.fromWireType(h(d))},enumerable:!0};g&&(g=W(k,g),r.set=u=>{var t=[];g(d,p.toWireType(t,u));gb(t)});Object.defineProperty(l.J.constructor,b,r);return[]});return[]})},d:function(a,b,c,d,e,h){0<b||z();var k=ib(b,c);e=W(d,e);O([],[a],function(g){g=g[0];var l=`constructor ${g.name}`;void 0===g.J.U&&(g.J.U=[]);if(void 0!==g.J.U[b-1])throw new L(`Cannot register multiple constructors with identical number of parameters (${b-
1}) for class '${g.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);g.J.U[b-1]=()=>{Y(`Cannot construct ${g.name} due to unbound types`,k)};O([],k,function(n){n.splice(1,0,null);g.J.U[b-1]=hb(l,n,null,e,h);return[]});return[]})},a:function(a,b,c,d,e,h,k,g){var l=ib(c,d);b=I(b);h=W(e,h);O([],[a],function(n){function m(){Y(`Cannot call ${p} due to unbound types`,l)}n=n[0];var p=`${n.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);
g&&n.J.ua.push(b);var r=n.J.T,u=r[b];void 0===u||void 0===u.N&&u.className!==n.name&&u.W===c-2?(m.W=c-2,m.className=n.name,r[b]=m):(Ta(r,b,p),r[b].N[c-2]=m);O([],l,function(t){t=hb(p,t,n,h,k);void 0===r[b].N?(t.W=c-2,r[b]=t):r[b].N[c-2]=t;return[]});return[]})},b:function(a,b,c,d,e,h,k,g,l,n){b=I(b);e=W(d,e);O([],[a],function(m){m=m[0];var p=`${m.name}.${b}`,r={get:function(){Y(`Cannot access ${p} due to unbound types`,[c,k])},enumerable:!0,configurable:!0};r.set=l?()=>{Y(`Cannot access ${p} due to unbound types`,
[c,k])}:()=>{M(p+" is a read-only property")};Object.defineProperty(m.J.T,b,r);O([],l?[c,k]:[c],function(u){var t=u[0],w={get:function(){var N=jb(this,m,p+" getter");return t.fromWireType(e(h,N))},enumerable:!0};if(l){l=W(g,l);var H=u[1];w.set=function(N){var y=jb(this,m,p+" setter"),ca=[];l(n,y,H.toWireType(ca,N));gb(ca)}}Object.defineProperty(m.J.T,b,w);return[]});return[]})},y:function(a,b){b=I(b);P(a,{name:b,fromWireType:function(c){var d=mb(c);lb(c);return d},toWireType:function(c,d){return U(d)},
argPackAdvance:8,readValueFromPointer:ab,S:null})},s:function(a,b,c){c=Ba(c);b=I(b);P(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,e){return e},argPackAdvance:8,readValueFromPointer:nb(b,c),S:null})},f:function(a,b,c,d,e){b=I(b);-1===e&&(e=4294967295);e=Ba(c);var h=g=>g;if(0===d){var k=32-8*c;h=g=>g<<k>>>k}c=b.includes("unsigned")?function(g,l){return l>>>0}:function(g,l){return l};P(a,{name:b,fromWireType:h,toWireType:c,argPackAdvance:8,readValueFromPointer:ob(b,e,0!==d),S:null})},
g:function(a,b,c){function d(h){h>>=2;var k=D;return new e(k.buffer,k[h+1],k[h])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=I(c);P(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{sa:!0})},p:function(a,b){b=I(b);var c="std::string"===b;P(a,{name:b,fromWireType:function(d){var e=D[d>>2],h=d+4;if(c)for(var k=h,g=0;g<=e;++g){var l=h+g;if(g==e||0==A[l]){k=k?ya(k,l-k):"";if(void 0===n)var n=k;else n+=String.fromCharCode(0),
n+=k;k=l+1}}else{n=Array(e);for(g=0;g<e;++g)n[g]=String.fromCharCode(A[h+g]);n=n.join("")}X(d);return n},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var h,k="string"==typeof e;k||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array||M("Cannot pass non-string to std::string");var g;if(c&&k)for(h=g=0;h<e.length;++h){var l=e.charCodeAt(h);127>=l?g++:2047>=l?g+=2:55296<=l&&57343>=l?(g+=4,++h):g+=3}else g=e.length;h=g;g=Eb(4+h+1);l=g+4;D[g>>2]=h;
if(c&&k){if(k=l,l=h+1,h=A,0<l){l=k+l-1;for(var n=0;n<e.length;++n){var m=e.charCodeAt(n);if(55296<=m&&57343>=m){var p=e.charCodeAt(++n);m=65536+((m&1023)<<10)|p&1023}if(127>=m){if(k>=l)break;h[k++]=m}else{if(2047>=m){if(k+1>=l)break;h[k++]=192|m>>6}else{if(65535>=m){if(k+2>=l)break;h[k++]=224|m>>12}else{if(k+3>=l)break;h[k++]=240|m>>18;h[k++]=128|m>>12&63}h[k++]=128|m>>6&63}h[k++]=128|m&63}}h[k]=0}}else if(k)for(k=0;k<h;++k)n=e.charCodeAt(k),255<n&&(X(l),M("String has UTF-16 code units that do not fit in 8 bits")),
A[l+k]=n;else for(k=0;k<h;++k)A[l+k]=e[k];null!==d&&d.push(X,g);return g},argPackAdvance:8,readValueFromPointer:ab,S:function(d){X(d)}})},o:function(a,b,c){c=I(c);if(2===b){var d=rb;var e=sb;var h=tb;var k=()=>ia;var g=1}else 4===b&&(d=ub,e=vb,h=wb,k=()=>D,g=2);P(a,{name:c,fromWireType:function(l){for(var n=D[l>>2],m=k(),p,r=l+4,u=0;u<=n;++u){var t=l+4+u*b;if(u==n||0==m[t>>g])r=d(r,t-r),void 0===p?p=r:(p+=String.fromCharCode(0),p+=r),r=t+b}X(l);return p},toWireType:function(l,n){"string"!=typeof n&&
M(`Cannot pass non-string to C++ string type ${c}`);var m=h(n),p=Eb(4+m+b);D[p>>2]=m>>g;e(n,p+4,m+b);null!==l&&l.push(X,p);return p},argPackAdvance:8,readValueFromPointer:ab,S:function(l){X(l)}})},x:function(a,b){b=I(b);P(a,{Ca:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},j:function(a,b,c){a=mb(a);b=xb(b,"emval::as");var d=[],e=U(d);D[c>>2]=e;return b.toWireType(d,a)},e:lb,l:function(a,b){a=mb(a);b=mb(b);return U(a[b])},m:function(a){var b=yb[a];return U(void 0===
b?I(a):b)},i:function(a){var b=mb(a);gb(b);lb(a)},r:function(a,b){a=xb(a,"_emval_take_value");a=a.readValueFromPointer(b);return U(a)},q:function(){z("")},n:function(a,b,c){zb.length=0;var d;for(c>>=2;d=A[b++];)c+=105!=d&c,zb.push(105==d?C[c]:ka[c++>>1]),++c;return za[a].apply(null,zb)},w:function(a){var b=A.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,d);a:{e=e.min.call(e,2147483648,d+(65536-d%65536)%65536)-ea.buffer.byteLength+
65535>>>16;try{ea.grow(e);la();var h=1;break a}catch(k){}h=void 0}if(h)return!0}return!1},u:Ab,t:Bb};
(function(){function a(c){c=c.exports;f.asm=c;ea=f.asm.A;la();ma=f.asm.C;oa.unshift(f.asm.B);E--;f.monitorRunDependencies&&f.monitorRunDependencies(E);if(0==E&&(null!==ra&&(clearInterval(ra),ra=null),F)){var d=F;F=null;d()}return c}var b={a:Fb};E++;f.monitorRunDependencies&&f.monitorRunDependencies(E);if(f.instantiateWasm)try{return f.instantiateWasm(b,a)}catch(c){v("Module.instantiateWasm callback failed with error: "+c),ba(c)}xa(b,function(c){a(c.instance)}).catch(ba);return{}})();
function Eb(){return(Eb=f.asm.D).apply(null,arguments)}function X(){return(X=f.asm.E).apply(null,arguments)}function fb(){return(fb=f.asm.F).apply(null,arguments)}f.__embind_initialize_bindings=function(){return(f.__embind_initialize_bindings=f.asm.G).apply(null,arguments)};f._sbrk=function(){return(f._sbrk=f.asm.H).apply(null,arguments)};f.___heap_base=89344;var Gb;F=function Hb(){Gb||Ib();Gb||(F=Hb)};
function Ib(){function a(){if(!Gb&&(Gb=!0,f.calledRun=!0,!fa)){Aa(oa);aa(f);if(f.onRuntimeInitialized)f.onRuntimeInitialized();if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var b=f.postRun.shift();pa.unshift(b)}Aa(pa)}}if(!(0<E)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)qa();Aa(na);0<E||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);a()},1)):a())}}
if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();Ib();function Jb(){const a=f.ka?f.ka(0):0,b=f.ha?f.ha.length:0;return{ra:a,qa:b,pa:b-a,get Ba(){return(this.ra/1024/1024).toFixed(2)},get Aa(){return(this.qa/1024/1024).toFixed(2)},get za(){return(this.pa/1024/1024).toFixed(2)}}}"undefined"!==typeof globalThis&&(globalThis.getSpineMemoryInfo=Jb);"undefined"!==typeof f&&(f.getSpineMemoryInfo=Jb);console.log("[Spine] getSpineMemoryInfo \u5df2\u6ce8\u518c");


  return spineWasm.ready
}

);
})();
export default spineWasm;